### ISSUE TITLE
Getting following error

### ISSUE THREAD

**Issue by iveeshal** [matehat/cqerl#53] opened 2015-06-29 19:27 UTC
Hi ,

I tried `cqerl:new_client({}).` on the erlang shell and I get following error.Do you see any potential reasons.

```erlang
 cqerl:new_client({}).
== Starting CQErl frontend. ==
00:55:20.748 [debug] Supervisor pooler_g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk_pool_sup started pooler_pooled_worker_sup:start_link({pool,g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk,cqerl,5,2,{cqerl_client,start_link,[{{127,0,0,1},...},...]},...}) at pid <0.543.0>
** exception exit: {{noproc,{gen_server,call,
                                        [g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk,
                                         {take_member,0},
                                         infinity]}},
                    {gen_server,call,
                                [cqerl,{get_client,{{127,0,0,1},9042},[]}]}}
     in function  gen_server:call/2 (gen_server.erl, line 204)
(ejabberd@L-9LCS022)2> 00:55:20.748 [error] Supervisor pooler_g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk_pool_sup had child undefined started with pooler:start_link({pool,g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk,cqerl,5,2,{cqerl_client,start_link,[{{127,0,0,1},...},...]},...}) at undefined exit with reason {'EXIT',{function_clause,[{pooler,start_link,[{pool,g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk,cqerl,5,2,{cqerl_client,start_link,[{{127,0,0,1},9042},[{auth,{cqerl_auth_plain_handler,[]}},{ssl,false},{sleep_duration,{15.0,sec}},{keyspace,undefined}]]},[],0,0,1,{1,min},{15.0,sec},undefined,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},...},...}],...},...]}} in context start_error
00:55:20.748 [error] gen_server cqerl terminated with reason: no such process or port in call to gen_server:call(g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk, {take_member,0}, infinity) in gen_server:call/3 line 212
00:55:20.748 [error] CRASH REPORT Process cqerl with 0 neighbours exited with reason: no such process or port in call to gen_server:call(g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk, {take_member,0}, infinity) in gen_server:terminate/7 line 826
00:55:20.748 [error] Supervisor cqerl_sup had child undefined started with cqerl:start_link() at <0.147.0> exit with reason no such process or port in call to gen_server:call(g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk, {take_member,0}, infinity) in context child_terminated
00:55:20.748 [debug] Supervisor cqerl_sup started cqerl:start_link() at pid <0.544.0>
```

**Comment by iveeshal** [comment] 2015-06-30 04:37
on typing

 application:ensure_all_started(cqerl).


09:36:10.959 [debug] Supervisor pooler_sup started pooler_starter_sup:start_link() at pid <0.531.0>
09:36:10.959 [info] Application pooler started on node 'ejabberd@L-9LCS022'
== Starting CQErl frontend. ==
09:36:10.962 [debug] Supervisor cqerl_sup started cqerl:start_link() at pid <0.536.0>
09:36:10.964 [debug] Supervisor cqerl_sup started cqerl_cache:start_link() at pid <0.537.0>
09:36:10.967 [debug] Supervisor cqerl_sup started cqerl_batch_sup:start_link() at pid <0.538.0>
09:36:10.970 [debug] Supervisor cqerl_sup started cqerl_processor_sup:start_link() at pid <0.539.0>
{ok,[pooler,cqerl]}

This works fine.

**Comment by matehat** [comment] 2015-11-05 14:10
Sorry for the insane delay. Did you get this working?

**Comment by matehat** [comment] 2015-12-18 15:42
No more details for this error and I could not reproduce, so closing.

**Closed by matehat** 2015-12-18 15:42 UTC
Labels: question, wontfix
